openapi: 3.0.0
info:
  title: Self integration API
  description: "Self integration API"
  version: 0.0.1
servers:
  - url: /consortia/{consortiumId}/
paths:
  /_self:
    get:
      summary: Get a list of user tenants associated to the logged in user
      operationId: getUserTenantsForCurrentUser
      parameters:
        - $ref: "#/components/parameters/consortiumId"
      responses:
        "200":
          $ref: "#/components/responses/UserTenantCollection"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    UserTenantCollection:
      description: Returns a user tenant association collection object
      content:
        application/json:
          schema:
            $ref: "schemas/userTenant.yaml#/UserTenantCollection"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium
